:sy on
:set tabstop=4
:set expandtab
:set shiftwidth=4
:set hlsearch

" ps1 PowerShell
" https://github.com/PProvost/vim-ps1
:let g:ps1_nofold_blocks = 1
:let g:ps1_nofold_sig = 1

" Change the lineendings in the view:
"
" :e ++ff=dos
" :e ++ff=mac
" :e ++ff=unix

